# Generated by Django 2.2.11 on 2021-01-10 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='personals')),
            ],
            options={
                'verbose_name_plural': 'Personals',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('logo', models.ImageField(blank=True, upload_to='profilio/logo')),
                ('description', models.TextField(blank=True)),
                ('registeration_date', models.DateTimeField(auto_now_add=True)),
                ('created_on', models.DateField(blank=True, null=True)),
                ('on_trial', models.BooleanField(default=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('template_path', models.CharField(blank=True, default='default', max_length=30)),
                ('slug', models.SlugField(blank=True)),
            ],
            options={
                'verbose_name': 'Schools',
                'verbose_name_plural': 'Schools',
            },
        ),
        migrations.CreateModel(
            name='SchoolInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(blank=True, max_length=254, unique=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.School')),
            ],
            options={
                'verbose_name_plural': 'School Information',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_urls', models.CharField(max_length=400)),
                ('social_class', models.CharField(max_length=50)),
                ('school_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.SchoolInformation')),
            ],
            options={
                'verbose_name_plural': 'Social Links',
            },
        ),
        migrations.CreateModel(
            name='SingleFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=230)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.Personals')),
            ],
            options={
                'verbose_name_plural': 'Single Feature',
            },
        ),
        migrations.CreateModel(
            name='SchoolTestimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='school/testimonial/image')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.School')),
            ],
            options={
                'verbose_name_plural': "School's Testimonials",
            },
        ),
        migrations.CreateModel(
            name='SchoolTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('title', models.CharField(blank=True, max_length=400)),
                ('image', models.ImageField(blank=True, upload_to='school/teachers')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.School')),
            ],
            options={
                'verbose_name_plural': 'School Teachers',
            },
        ),
        migrations.CreateModel(
            name='SchoolService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40)),
                ('image', models.ImageField(blank=True, upload_to='school/service/image')),
                ('description', models.TextField(blank=True)),
                ('size_of_card', models.CharField(blank=True, max_length=10)),
                ('icon', models.CharField(blank=True, max_length=53)),
                ('code', models.CharField(blank=True, max_length=3)),
                ('tag', models.CharField(blank=True, max_length=10)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.School')),
            ],
            options={
                'verbose_name_plural': 'School Service',
            },
        ),
        migrations.CreateModel(
            name='SchoolNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=180)),
                ('image', models.ImageField(blank=True, upload_to='school/news')),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.School')),
            ],
            options={
                'verbose_name_plural': 'School News',
            },
        ),
        migrations.CreateModel(
            name='SchoolHomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(blank=True, max_length=40)),
                ('hero_text', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, upload_to='school/hero_image')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.School')),
            ],
            options={
                'verbose_name_plural': 'School Home',
            },
        ),
        migrations.CreateModel(
            name='SchoolAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_students', models.PositiveIntegerField(blank=True, null=True)),
                ('qualified_teachers', models.PositiveIntegerField(blank=True, null=True)),
                ('graduated_students', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.School')),
            ],
            options={
                'verbose_name_plural': "School's Achievements",
            },
        ),
        migrations.AddField(
            model_name='personals',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.School'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='school/gallery/')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.School')),
            ],
            options={
                'verbose_name_plural': 'Schools Gallery',
            },
        ),
        migrations.CreateModel(
            name='ContactSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('slug', models.SlugField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.School')),
            ],
            options={
                'verbose_name_plural': 'Contact Schools',
            },
        ),
        migrations.CreateModel(
            name='AboutSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(blank=True, upload_to='school/feature/image')),
                ('about', models.TextField(blank=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.School')),
            ],
            options={
                'verbose_name_plural': 'School About',
            },
        ),
    ]
